// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Sliders.API.Data.Migrations
{
    [DbContext(typeof(SlidersWebContext))]
    [Migration("20200220200911_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sliders.WebAPI.Models.SlidersData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<int>("Slider1")
                        .HasColumnType("int");

                    b.Property<int>("Slider2")
                        .HasColumnType("int");

                    b.Property<int>("Slider3")
                        .HasColumnType("int");

                    b.Property<int>("Slider4")
                        .HasColumnType("int");

                    b.Property<int>("Slider5")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SlidersData");
                });
#pragma warning restore 612, 618
        }
    }
}
